# This is DFT-forge TOML file
DFTtype = "OpenMX" #  OpenMX EcaJ Wannier90
#Wannier90type = "OpenMX" # OpenMX  VASP  EcalJ

spintype = "co_spin" #Set Spin type, para, co_spin, nc_spin

#result_file = "../examples/NiO/4cell/Ni6.0_O5.0-s2p2d2f1-4.25_0.0-4.180-k10/nio.scfout"
result_file = "nio.scfout"
atom12 = [[1,1],[1,2]]


# k,q for calculation. Using the same k,q points number is recomended
k_point_num = [6,6,6]
q_point_num = [6,6,6]

[orbitals]

##################################################################################################
#In OpenMX inputfile NiO.dat
#<Definition.of.Atomic.Species
#Ni     Ni6.0S-s2p2d2f1  Ni_PBE13S
##################################################################################################
# s2p2d2f1 represent 2 s orbitals, 2 p orbitals, 2 d orbitals, and 1 f orbital for the Ni.
# Therefore, orbital indexs 1,2 standsfor s1, s2
# 3,4,5: p1   5,6,7: p2
# 9,10,11,12,13: d1 14,15,16,17,18: d2
# 19,20,21,22,23,24,25: f1
#
# If we want to calculate the interaction between d orbitals of Ni,
# you can choose [9-13] orbital.
# Each orbital index names is as follows:
# 9:dz2, 10:dx2y2, 11:dxy, 12:dyz, 13:dxz
##################################################################################################

orbitalselection = false # true,false 
orbital_mask1_list = [[9],[10],[11],[12],[13]]
orbital_mask2_list = [[9],[10],[11],[12],[13]]

orbital_mask1_names = "[dz2,dx2y2,dxy,dyz,dxz]"
orbital_mask2_names = "[dz2,dx2y2,dxy,dyz,dxz]"



[bandplot]
bandplot = true

kPoint_step = 10
kPath_list = [
[[0.0   ,0.0    ,0.5    ],[ 0.0    , 0.5     ,  0.0    ],["Z2","Y"]],
[[0.0   ,0.5    ,0.0    ],[ 0.5    , 0.0     ,  0.0    ],["Y","X"]],
[[0.5   ,0.0    ,0.0    ],[ 0.0    , 0.0     ,  0.0    ],["X","G"]],
[[0.0   ,0.0    ,0.0    ],[ 0.5    , 0.5     ,  0.5    ],["G","Z"]],
[[0.5   ,0.5    ,0.5    ],[ 0.8125 , 0.34375 ,  0.34375],["Z","K"]],
[[0.8125,0.34375,0.34375],[ 0.1875 , -0.34375, -0.34375],["K","U"]]
]
